/*
 * main.c — Street Fighter II Recompiled entry point.
 *
 * Initializes the CPS1 runtime, registers all recompiled functions,
 * and enters the main game loop.
 */

#include <cps1recomp/cps1recomp.h>
#include <stdio.h>

/* Forward declarations for recompiled function registration */
/* #include "recomp/recomp_funcs.h" */

int main(int argc, char *argv[]) {
    const char *rom_path = "sf2.zip";
    int scale = 3;

    /* Parse command line */
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') {
            rom_path = argv[i];
        }
    }

    printf("Street Fighter II Recompiled\n");
    printf("============================\n");
    printf("ROM: %s\n\n", rom_path);

    /* Initialize the CPS1 runtime */
    cps1_config_t config = {
        .rom_path = rom_path,
        .window_scale = scale,
        .fullscreen = false,
        .vsync = true,
    };

    if (cps1_init(&config) != 0) {
        fprintf(stderr, "Failed to initialize CPS1 runtime\n");
        return 1;
    }

    /* Register recompiled functions at their original 68K addresses */
    /* TODO: Phase 2 - Generated by tools/generate_recomp.py
     *
     * recomp_register_all();
     *
     * This will register hundreds of functions like:
     *   func_table_register(0x000200, func_000200);  // reset handler
     *   func_table_register(0x000400, func_000400);  // main loop
     *   func_table_register(0x012A4C, func_012A4C);  // check_inputs
     *   ...
     */

    printf("[sf2] No recompiled functions registered yet (Phase 2)\n");
    printf("[sf2] Run tools/analyze_rom.py and tools/generate_recomp.py first\n");

    /* Enter the main loop (never returns) */
    cps1_run();

    /* Cleanup (unreachable in normal operation) */
    cps1_shutdown();
    return 0;
}
